### ISSUE TITLE
An uncaught Exception occurred on "pool-3-thread-1" thread.

### ISSUE THREAD

**Issue by devcodedao** [NativeScript/nativescript-background-http#276]
Hi everybody
After uploadfile appear err like below
`` An uncaught Exception occurred on "pool-3-thread-1" thread.
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/NotificationCompat$Builder;
	at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:467)
	at net.gotev.uploadservice.UploadTask.run(UploadTask.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.NotificationCompat$Builder" on path: DexPathList[[zip file "/data/app/my.com.pacificwise.dingdong-QB03D7-J_6TVeHEGvBvbIg==/base.apk"],nativeLibraryDirectories=[/data/app/my.com.pacificwise.dingdong-QB03D7-J_6TVeHEGvBvbIg==/lib/x86, /data/app/my.com.pacificwise.dingdong-QB03D7-J_6TVeHEGvBvbIg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 5 more
``
Please help me if you have anyidea!

**Comment by dodongphure** [comment]
Can close this issue? @datitk16
