### ISSUE TITLE
Error Receiving BroadCast Intent.

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-background-http#31]
java.lang.RuntimeException: Error receiving broadcast Intent { act=net.gotev.uploadservice.broadcast.status flg=0x10 (has extras) } in com.tns.gen.net.gotev.uploadservice.UploadServiceBroadcastReceiver_ftns_modules_nativescript-background-http_background-http_l6_c70__@66ab662
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 
Calling js method onError failed

TypeError: Cannot read property 'push' of undefined
File: "/data/data/org.nativescript.myapp/files/app/app.component.js, line: 43, column: 23

StackTrace: 
    Frame: function:'log

**Comment by Daxito** [comment]
Maybe your this.events variable is not defined, are you sure you have it defined somewhere? if so try not to use ```this```

**Comment by PanayotCankov** [comment]
Try with 2.4.0 we are about to publish today.

**Comment by neddinn** [comment]
Still having this issue. 
I'm using nativescript-background-http v3.0.0 & tns-core-modules v3.3.0
Its actually erratic and so when given the exact same file and environment, it might either fail or complete successfully.
