### ISSUE TITLE
Cannot upload selfies (image taken with front camera)

### ISSUE THREAD

**Issue by bachras** [NativeScript/nativescript-background-http#93]
Hi,

I am unable to upload photos taken with phone's front camera, all other images are working fine. Here is the error I get :
````
System.err: java.lang.RuntimeException: Error receiving broadcast Intent { act=net.gotev.uploadservice.broadcast.status flg=0x10 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 (has extras) } in com.tns.gen.net.gotev.uploadservice.UploadServiceBroadcastReceiver_ftns_modules_nativescript_background_http_background_http_l7_c79__@6086161
System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCompleted failed
System.err: 
System.err: SyntaxError: Unexpected token < in JSON at position 0
System.err: File: "<unknown>, line: 1, column: 0
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/org.xxxxx.xxxxx/files/app/pages/mainTabs/mainTabs.component.js', line: 1910, column: 26
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.xxxxx.xxxxx/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err: 	Frame: function:'onCompleted', file:'file:///data/data/org.xxxxx.xxxxx/files/app/tns_modules/nativescript-background-http/background-http.js', line: 38, column: 14
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.net.gotev.uploadservice.UploadServiceBroadcastReceiver_ftns_modules_nativescript_background_http_background_http_l7_c79__.onCompleted(UploadServiceBroadcastReceiver_ftns_modules_nativescript_background_http_background_http_l7_c79__.java:32)
System.err: 	at net.gotev.uploadservice.UploadServiceBroadcastReceiver.onReceive(UploadServiceBroadcastReceiver.java:36)
System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
System.err: 	... 7 more
ActivityManager: Process org.xxxxx.xxxxx (pid 11106) has died(185,1460)
ActivityManager: cleanUpApplicationRecord -- 11106
````

Has anybody had similar problem or have any suggestions? Any help is highly appreciated. Thank you

**Comment by bachras** [comment]
I just found out that the problem was on the server side and it was sending error message. It is solved now.
